// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SyncToAsync.Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "SyncToAsync.Extension.9a01841b-be97-49d6-a582-71671d3bade1";
        public const string Name = "SyncToAsync.Extension";
        public const string Description = @"A Visual Studio extension that creates a custom codelense to move from async method to its sync sibling method and vice versa.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "lsoft";
        public const string Tags = "";
    }
}
